site_name: sudheerchamarthi
repo_name: sudheerchamarthi/sudheerchamarthi.github.io
repo_url: https://github.com/sudheerchamarthi/sudheerchamarthi.github.io
theme:
  name: material
  palette:
    scheme: preference
    primary: red
    accent: indigo
plugins:
  - search:
  - minify:
      minify_html: true
  - git-revision-date-localized
  - awesome-pages
